### ISSUE TITLE
token自动刷新

### ISSUE THREAD

**Issue by KouShenhai** [KouShenhai/KCloud-Platform-IoT#214]

**Comment by KouShenhai** [comment]
重复刷新页面，确实有点损耗资源

**Comment by meimosor** [comment]
SAS Token续签有思路吗

**Comment by KouShenhai** [comment]
> SAS Token续签有思路吗

我给你画个流程图
![image](https://user-images.githubusercontent.com/48756217/232098111-9c015612-2a08-46f2-bc78-453ef5295e79.png)

**Comment by KouShenhai** [comment]
> SAS Token续签有思路吗

希望对你有所帮助

**Comment by KouShenhai** [comment]
> SAS Token续签有思路吗

如果没有什么疑问的话，我就关闭啦

**Comment by KouShenhai** [comment]
先关闭吧
