### ISSUE TITLE
添加数据库版本控制

### ISSUE THREAD

**Issue by livk-cloud** [KouShenhai/KCloud-Platform-IoT#252]

**Comment by KouShenhai** [comment]
liquibase目前不支持jdk17（裂开），先放着吧

**Comment by livk-cloud** [comment]
> liquibase目前不支持jdk17（裂开），先放着吧

> 支持的
![image](https://user-images.githubusercontent.com/50291874/232356594-9c7ee164-42e2-4c6f-9284-1ff98a7fdf68.png)

**Comment by KouShenhai** [comment]
> > liquibase目前不支持jdk17（裂开），先放着吧
> 
> > 支持的
> > ![image](https://user-images.githubusercontent.com/50291874/232356594-9c7ee164-42e2-4c6f-9284-1ff98a7fdf68.png)

我再看看吧，其实我也用不到

**Comment by KouShenhai** [comment]
目前使用flyway
