### ISSUE TITLE
功能

### ISSUE THREAD

**Issue by WUZHUHE38** [KouShenhai/KCloud-Platform-IoT#2948]
**问题描述（写清楚并附图）**

转载：

1.不良念头大多不是自己的，念头就起来了马上听听楞严咒 文殊菩萨戒淫咒，声音大点。自己一个人的话大声念出 南无观世音菩萨 南无莲花尊丰如来 南无无忧最胜吉祥如来，南无月光如来等等。

2.履戒履破是业力！业力不敌愿力，发大愿世人皆戒除邪淫，平时有意或者无意碰到了不良网站都举报，多转发评论劝人戒淫，欲望顿消，亲测最有效的方法。

3.妨碍戒淫和身体恢复的很大障碍是手机。张至顺道长说“人一身之精在眼，伤眼就是伤命。”刷手机极其消耗精气神让身体难以恢复，并且有很多黄源让人防不胜防。希望大家尽量别熬夜，减少手机使用。

4.有意识的接触一些各家经典，比如文昌帝君戒淫宝训，地藏经，观世音菩萨普门品等等。

5.看言情小说，属于邪淫中的意淫，勿以恶小而为之，坚决断除不良习惯。

6.任何问题的产生，我们都应该从源头上下手，从因联想到果，从果上切除因！

如今的网络信息如此的发达，一句话一篇文章发出去，可以有无数的人看到。一个人如果发送一些不良的信息，让无数人看到产生的恶果是非常严重的，造恶是非常迅速的，而且后果很严重。但是反过来，一个人要迅速的扭转自己的命运，也是可以在网络行善啊！一发出去，马上会有成千上万的人看得到，也会有很多的人回头，这就是网络道场的功德和利益。只要不停的去转发，SY肯定不会再犯。

其实在网络上转载发布，是件非常容易的事情，但是实际带来的效果却超出了我们的思维范围！特别是那些XY超重的地方，只要是网络能够看得到的地方都可以发布这些功德帖子!

**Comment by KouShenhai** [comment]
> **问题描述（写清楚并附图）**
> 
> 转载：
> 
> 1.不良念头大多不是自己的，念头就起来了马上听听楞严咒 文殊菩萨戒淫咒，声音大点。自己一个人的话大声念出 南无观世音菩萨 南无莲花尊丰如来 南无无忧最胜吉祥如来，南无月光如来等等。
> 
> 2.履戒履破是业力！业力不敌愿力，发大愿世人皆戒除邪淫，平时有意或者无意碰到了不良网站都举报，多转发评论劝人戒淫，欲望顿消，亲测最有效的方法。
> 
> 3.妨碍戒淫和身体恢复的很大障碍是手机。张至顺道长说“人一身之精在眼，伤眼就是伤命。”刷手机极其消耗精气神让身体难以恢复，并且有很多黄源让人防不胜防。希望大家尽量别熬夜，减少手机使用。
> 
> 4.有意识的接触一些各家经典，比如文昌帝君戒淫宝训，地藏经，观世音菩萨普门品等等。
> 
> 5.看言情小说，属于邪淫中的意淫，勿以恶小而为之，坚决断除不良习惯。
> 
> 6.任何问题的产生，我们都应该从源头上下手，从因联想到果，从果上切除因！
> 
> 如今的网络信息如此的发达，一句话一篇文章发出去，可以有无数的人看到。一个人如果发送一些不良的信息，让无数人看到产生的恶果是非常严重的，造恶是非常迅速的，而且后果很严重。但是反过来，一个人要迅速的扭转自己的命运，也是可以在网络行善啊！一发出去，马上会有成千上万的人看得到，也会有很多的人回头，这就是网络道场的功德和利益。只要不停的去转发，SY肯定不会再犯。
> 
> 其实在网络上转载发布，是件非常容易的事情，但是实际带来的效果却超出了我们的思维范围！特别是那些XY超重的地方，只要是网络能够看得到的地方都可以发布这些功德帖子!

不是，哥们，你这是干啥呀

**Comment by WUZHUHE38** [comment]
> **问题描述（写清楚并附图）**
> 
> 转载：
> 
> 1.不良念头大多不是自己的，念头就起来了马上听听楞严咒 文殊菩萨戒淫咒，声音大点。自己一个人的话大声念出 南无观世音菩萨 南无莲花尊丰如来 南无无忧最胜吉祥如来，南无月光如来等等。
> 
> 2.履戒履破是业力！业力不敌愿力，发大愿世人皆戒除邪淫，平时有意或者无意碰到了不良网站都举报，多转发评论劝人戒淫，欲望顿消，亲测最有效的方法。
> 
> 3.妨碍戒淫和身体恢复的很大障碍是手机。张至顺道长说“人一身之精在眼，伤眼就是伤命。”刷手机极其消耗精气神让身体难以恢复，并且有很多黄源让人防不胜防。希望大家尽量别熬夜，减少手机使用。
> 
> 4.有意识的接触一些各家经典，比如文昌帝君戒淫宝训，地藏经，观世音菩萨普门品等等。
> 
> 5.看言情小说，属于邪淫中的意淫，勿以恶小而为之，坚决断除不良习惯。
> 
> 6.任何问题的产生，我们都应该从源头上下手，从因联想到果，从果上切除因！
> 
> 如今的网络信息如此的发达，一句话一篇文章发出去，可以有无数的人看到。一个人如果发送一些不良的信息，让无数人看到产生的恶果是非常严重的，造恶是非常迅速的，而且后果很严重。但是反过来，一个人要迅速的扭转自己的命运，也是可以在网络行善啊！一发出去，马上会有成千上万的人看得到，也会有很多的人回头，这就是网络道场的功德和利益。只要不停的去转发，SY肯定不会再犯。
> 
> 其实在网络上转载发布，是件非常容易的事情，但是实际带来的效果却超出了我们的思维范围！特别是那些XY超重的地方，只要是网络能够看得到的地方都可以发布这些功德帖子!

**Comment by WUZHUHE38** [comment]
> **问题描述（写清楚并附图）**
> 
> 转载：
> 
> 1.不良念头大多不是自己的，念头就起来了马上听听楞严咒 文殊菩萨戒淫咒，声音大点。自己一个人的话大声念出 南无观世音菩萨 南无莲花尊丰如来 南无无忧最胜吉祥如来，南无月光如来等等。
> 
> 2.履戒履破是业力！业力不敌愿力，发大愿世人皆戒除邪淫，平时有意或者无意碰到了不良网站都举报，多转发评论劝人戒淫，欲望顿消，亲测最有效的方法。
> 
> 3.妨碍戒淫和身体恢复的很大障碍是手机。张至顺道长说“人一身之精在眼，伤眼就是伤命。”刷手机极其消耗精气神让身体难以恢复，并且有很多黄源让人防不胜防。希望大家尽量别熬夜，减少手机使用。
> 
> 4.有意识的接触一些各家经典，比如文昌帝君戒淫宝训，地藏经，观世音菩萨普门品等等。
> 
> 5.看言情小说，属于邪淫中的意淫，勿以恶小而为之，坚决断除不良习惯。
> 
> 6.任何问题的产生，我们都应该从源头上下手，从因联想到果，从果上切除因！
> 
> 如今的网络信息如此的发达，一句话一篇文章发出去，可以有无数的人看到。一个人如果发送一些不良的信息，让无数人看到产生的恶果是非常严重的，造恶是非常迅速的，而且后果很严重。但是反过来，一个人要迅速的扭转自己的命运，也是可以在网络行善啊！一发出去，马上会有成千上万的人看得到，也会有很多的人回头，这就是网络道场的功德和利益。只要不停的去转发，SY肯定不会再犯。
> 
> 其实在网络上转载发布，是件非常容易的事情，但是实际带来的效果却超出了我们的思维范围！特别是那些XY超重的地方，只要是网络能够看得到的地方都可以发布这些功德帖子!

**Comment by WUZHUHE38** [comment]
多多益善

**Comment by KouShenhai** [comment]
> 多多益善

我还以为是有人提issue，有什么问题需要咨询呢，还是少发与项目无关的玩意儿，给作者带来不必要的困扰
