### ISSUE TITLE
免登陆的URL能实现统一管理

### ISSUE THREAD

**Issue by liukefu2050** [KouShenhai/KCloud-Platform-IoT#307]
**Is your feature request related to a problem? Please describe.**
gateway 中配置 ignore.uris 选项，貌似只能对laokou-auth 项目起作用。其他项目laokou-admin 等不起作用
请求免登陆接口，依然返回：

{"code":401,"msg":"登录状态已过期，请重新登录","data":null}

**Describe the solution you'd like**
期望免登陆URL能统一通过gateway 管理
**Describe alternatives you've considered**
无
**Additional context**
无

**Comment by KouShenhai** [comment]
需要在gateway放行url，还需要在相应的应用放开url
以laokou-admin为例
![image](https://github.com/KouShenhai/KCloud-Platform-Alibaba/assets/48756217/74bec647-0a27-4fd6-9717-194561d784b3)

详情提交，请查看 @liukefu2050 #308

**Comment by KouShenhai** [comment]
公共配置放到nacos啦
