### ISSUE TITLE
我好像没有找到前端项目 只是UI对应的那部分吗

### ISSUE THREAD

**Issue by YesLoser** [KouShenhai/KCloud-Platform-IoT#3096]
**问题描述（写清楚并附图）**
如题：我好像没有找到前端项目 只是UI对应的那部分吗
我看开发计划中实现的功能很多  请问只是针对于后端吗

**Comment by KouShenhai** [comment]
改了前端框架，很多页面还没画

**Comment by YesLoser** [comment]
了解  麻烦再问一下，新的前端框架是指react吗？为什么不是热门的vue+ElementUI,是有什么方面的考虑？我主要是后端开发，而且看到项目架构分布非常明晰，感觉后端应该很nice。前端只是对vue有些了解react有些吃力，所以想请问对于前端这块是怎么计划的？感谢

**Comment by KouShenhai** [comment]
目前，我还要写cola的文章，没多余时间更新代码

**Comment by KouShenhai** [comment]
> 了解  麻烦再问一下，新的前端框架是指react吗？为什么不是热门的vue+ElementUI,是有什么方面的考虑？我主要是后端开发，而且看到项目架构分布非常明晰，感觉后端应该很nice。前端只是对vue有些了解react有些吃力，所以想请问对于前端这块是怎么计划的？感谢

react学起来也很快，使用umi写项目很快，考虑切换到react，是因为需要使用ant design Pro，用来构建复杂的页面，再者，react比较vue页面渲染快，很适合在带宽不太行的服务上面运行

**Comment by YesLoser** [comment]
明白，我对于前端也是一知半解，所以用哪种来学习都还好。后端环境已经搭建，抽时间看下前端  感谢回复  希望能吃透大佬的项目

**Comment by KouShenhai** [comment]
> 明白，我对于前端也是一知半解，所以用哪种来学习都还好。后端环境已经搭建，抽时间看下前端  感谢回复  希望能吃透大佬的项目

好，有问题就提issue

**Comment by KouShenhai** [comment]
关闭issue
