### ISSUE TITLE
swagger组件中openapi元配置在application.yml文件无法获取

### ISSUE THREAD

**Issue by wanglel** [KouShenhai/KCloud-Platform-IoT#525]
swagger组件中openapi元配置在application.yml或者propertis文件中带不出来这个元配置，举例flowable服务依赖了swagger的组件
<img width="1208" alt="image" src="https://github.com/KouShenhai/KCloud-Platform-Alibaba/assets/18409930/ed360b6c-7245-4aa2-884d-e912aaf9f4d9">

**Comment by KouShenhai** [comment]
无法复现
