### ISSUE TITLE
业务驱动开发，基于该项目构建物联网平台

### ISSUE THREAD

**Issue by KouShenhai** [KouShenhai/KCloud-Platform-IoT#591]

**Comment by KouShenhai** [comment]
1.cola改造（进行中）
2.mqtt（学习与实践）
3.netty实践
4.物联网相关技术（积累）

**Comment by KouShenhai** [comment]
项目地址：https://github.com/KouShenhai/KCloud-Platform-Iot

**Comment by JerryMeeet** [comment]
优秀！向大佬学习

**Comment by KouShenhai** [comment]
> 优秀！向大佬学习

感谢支持

**Comment by KouShenhai** [comment]
https://github.com/KouShenhai/KCloud-Platform-Alibaba/issues/1248
