### ISSUE TITLE
封装redis redistemplate被重复注册报错

### ISSUE THREAD

**Issue by ConanGao-gs** [KouShenhai/KCloud-Platform-IoT#975]
![image](https://github.com/KouShenhai/KCloud-Platform-Alibaba/assets/78586530/90dc74e7-5fe4-4c86-8497-394c9927c3b1)
![image](https://github.com/KouShenhai/KCloud-Platform-Alibaba/assets/78586530/09da60ea-3933-4543-8d5a-a0cedcf15cac)
存在redistemplate bean重复注册报错，该怎么解决

**Comment by KouShenhai** [comment]
需要使用redisUtil
